dbt_spotify_manipulator:
  target: prod
  outputs:
    prod:
      type: trino
      threads: 4
      host: trino-coordinator # 'trino-coordinator' | 'localhost' for local tests
      port: 8090 # 8085 if calling from host | 8090 for usage inside kubernetes
      user: admin
      catalog: minio
      schema: prod
      connection_method: direct